# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Hooligans' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Stomp
  pod 'StompClientLib'

  # SwiftLint
  pod 'SwiftLint'

  # SnapKit
  pod 'SnapKit', '~>5.0.0'

  # Pods for Hooligans

end
